# Generated by Django 3.1.4 on 2021-01-02 13:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='posts',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
