# Generated by Django 3.1.6 on 2021-02-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('publish',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='approved',
            new_name='status',
        ),
    ]
