# Generated by Django 3.1.4 on 2021-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210102_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='excerpt',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
